[package]
name = "rdkit-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
pkg-config = "0.3.9"
cmake = { version = "0.1.0" }
bindgen = "^0.59.2"