[package]
name = "rdkit-sys"
authors = ["Xavier Lange (xrlange@gmail.com)", "chrissly31415"]
version = "0.1.4"
edition = "2021"
license = "MIT"
description = "RDKit CFFI library builder and bindings"
repository = "https://github.com/tureus/rdkit-sys"
exclude = ["rdkit"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"]}
serde_json = "1"
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.9"
cmake = { version = "0.1.0" }
bindgen = "^0.59.2"
env_logger = "0"